apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgres-pvc
  namespace: authentik
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-nvme
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-pvc
  namespace: authentik
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-nvme
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media-pvc
  namespace: authentik
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-nvme
  resources:
    requests:
      storage: 5Gi
