apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: nextcloud
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "REPLACE_WITH_openssl_rand_hex_32"
  MYSQL_PASSWORD: "REPLACE_WITH_openssl_rand_hex_32"
  NEXTCLOUD_ADMIN_PASSWORD: "REPLACE_WITH_openssl_rand_hex_16"
