apiVersion: v1
kind: Secret
metadata:
  name: npm-secret
  namespace: npm
type: Opaque
stringData:
  DB_ROOT_PASSWORD: "REPLACE_WITH_openssl_rand_hex_32"
  DB_PASSWORD: "REPLACE_WITH_openssl_rand_hex_32"
