apiVersion: v1
kind: Secret
metadata:
  name: karakeep-secret
  namespace: karakeep
type: Opaque
stringData:
  NEXTAUTH_SECRET: "REPLACE_WITH_openssl_rand_hex_32"
  MEILI_MASTER_KEY: "REPLACE_WITH_openssl_rand_hex_32"
  # OPENAI_API_KEY: "sk-..."
