# kubectl create secret generic immich-secret --namespace immich \
#   --from-literal=DB_PASSWORD="$(openssl rand -hex 32)"
apiVersion: v1
kind: Secret
metadata:
  name: immich-secret
  namespace: immich
type: Opaque
stringData:
  DB_PASSWORD: "REPLACE_WITH_openssl_rand_hex_32"
